manager/urls.py
from django.urls import path
from manager import views

app_name = "manager"

urlpatterns = [
    
   path("", views.index, name="index"),
   path("login/", views.login, name="login"),
   path("logout/", views.logout, name="logout"),
   path("slider/", views.slider, name="slider"),
   path("slider_add", views.slider_add, name="slider_add"),
   path("slider_edit/<int:id>/", views.slider_edit, name="slider_edit"),
   path("slider_delete/<int:id>/", views.slider_delete, name="slider_delete"), 
   path("users/", views.users, name="users"),
   path("users_delete/<int:id>/", views.users_delete, name="users_delete"),
   path("users_edit/<int:id>/", views.users_edit, name="users_edit"),
   path("users_add/", views.users_add, name="users_add"),
   path("offers/", views.offers, name="offers"),
   path("offers_add", views.offers_add, name="offers_add"),
   path("offers_edit/<int:id>/", views.offers_edit, name="offers_edit"),
   path("offers_delete/<int:id>/", views.offers_delete, name="offers_delete"),
   path("flight/", views.flight, name="flight"),
   path("flight_add", views.flight_add, name="flight_add"),
   path("flight_edit/<int:id>/", views.flight_edit, name="flight_edit"),
   path("flight_delete/<int:id>/", views.flight_delete, name="flight_delete"),
   path("bus/", views.bus, name="bus"),
   path("bus_add", views.bus_add, name="bus_add"),
   path("bus_edit/<int:id>/", views.bus_edit, name="bus_edit"),
   path("bus_delete/<int:id>/", views.bus_delete, name="bus_delete"),
   path("train/", views.train, name="train"),
   path("train_add", views.train_add, name="train_add"),
   path("train_edit/<int:id>/", views.train_edit, name="train_edit"),
   path("train_delete/<int:id>/", views.train_delete, name="train_delete"),
]

transportion/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("web.urls", namespace="web")),
    path('manager/', include("manager.urls", namespace="manager"))
    
]



if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

web/urls.py
from django.urls import path
from web import views

app_name = "web"

urlpatterns = [
   path("", views.index, name="index"),
   path("flight", views.flight, name="flight"),
   path("", views.index, name="index"),
   path("login/", views.login, name="login"),
   path("register/", views.register, name="register"),
   path("logout/", views.logout, name="logout"),
   path("validate_email/", views.validate_email, name="validate_email"),
   path("train/", views.train, name="train"),
   path("train-search/", views.train_search, name="train-search"),
   path("bus/", views.bus, name="bus"),
   path("bus-search/", views.bus_search, name="bus-search"),
   path("flight-books/<int:id>/", views.flight_books, name="flight-books"),
   path("offer/", views.offer, name="offer"),
   path("train-books/", views.train_books, name="train-books"),
   path("bus-books/<int:id>/", views.bus_books, name="bus-books"),
   path("bus-seat/", views.bus_seat, name="bus-seat"),
   path("train-seat/", views.train_seat, name="train-seat"),
   path("flight-class/<int:id>/", views.flight_class, name="flight-class"),
   path("flight-details/", views.flight_details, name="flight-details"),
   path('seat_selection/<int:id>/', views.seat_selection, name='seat_selection'),
   
]

manager/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from users.manager import UserManager


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, max_length=256, error_messages={'unique': 'email aleardy exists'})
    is_customer = models.BooleanField(default=False)
    is_store = models.BooleanField(default=False)
    is_agent = models.BooleanField(default=False)
    is_manager = models.BooleanField(default=False)
    
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []
    
    objects = UserManager()
    
    class meta:
        db_table = "users_user"
        verbose_name = "User"
        verbose_name_plural = "Users"
        ordering = ['-id']
        
    def __str__(self):
        return self.email

manager/views.py
from django.shortcuts import render, reverse, redirect
from web.models import *
from django.http import HttpResponseRedirect, HttpResponse
from manager.forms import *
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from main.functions import generate_form_errors
from main.decorators import allow_manager


@allow_manager
@login_required(login_url='/login/')
def index(request):
    
    return render(request,'manager/index.html')

def login(request):
    if request.method == "POST":
        form = ManagerLoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(request, email=email, password=password)

            if user is not None:
                if user.is_manager: 
                    auth_login  (request,user)
                    return redirect('manager:index') 
                else:
                    messages.error(request, "Unauthorized access.")
                    return HttpResponse("unauthorized", status=401)
            else:
                messages.error(request, "Invalid email or password")
        else:
            messages.error(request, "Form is invalid.")
    else:
        form = ManagerLoginForm()

    return render(request, 'manager/login.html', {'form': form})


def logout(request):
    return redirect('manager:login')


@allow_manager
@login_required(login_url='/login/')
def slider(request):
    instances = Slider.objects.all()
    
    context = {
        'instances': instances,
    }
    
    
    return render(request,'manager/slider.html', context=context)
@allow_manager
@login_required(login_url='/login/')

def slider_delete(request,id):
    instance = Slider.objects.get(id=id)
    
    instance.delete()
    
    return HttpResponseRedirect(reverse('manager:slider'))
@allow_manager
@login_required(login_url='/login/')
def slider_add(request,):
    if request.method == 'POST':   
        form = SliderForm(request.POST, request.FILES)
        if form.is_valid():
            instance=form.save(commit=False)
            instance.save()
            
            return HttpResponseRedirect(reverse('manager:slider'))
            
        else:
            message = generate_form_errors(form)
            form = SliderForm()

            context = {
            "error": True,
            "message": message,
            "form": form,
            }
    
        return render(request,'manager/slider_add.html', context=context)



    else:
        form = SliderForm()
        
        context = {
            "form": form,
        }
        
    return render(request,'manager/slider_add.html', context=context)
@allow_manager
@login_required(login_url='/login/')
def slider_edit(request,id):
    instance = Slider.objects.get(id=id)
    if request.method == 'POST':   
        form = SliderForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            instance=form.save(commit=False)
            instance.save()
            
            return HttpResponseRedirect(reverse('manager:slider'))
            
        else:
            message = generate_form_errors(form)
            form = SliderForm()

            context = {
            "error": True,
            "message": message,
            "form": form,
            "instance": instance
            }
    
        return render(request,'manager/slider_add.html', context=context)



    else:
        form = SliderForm(instance=instance)
        
        context = {
            "form": form,
            "instance": instance
        }
        
    return render(request,'manager/slider_add.html', context=context)



@allow_manager
@login_required(login_url='/login/')
def users(request):
    instances = User.objects.all()
    
    context = {
        'instances': instances,
    }
    
    return render(request,'manager/users.html', context=context)

@allow_manager
@login_required(login_url='/login/')

def users_delete(request, id):
    instance = User.objects.get(id=id)
    
    instance.delete()
    
    return HttpResponseRedirect(reverse('manager:users'))
@allow_manager
@login_required(login_url='/login/')

def users_add(request):
    if request.method == 'POST':   
        form = UserForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            
            return HttpResponseRedirect(reverse('manager:users'))
        else:
            message = generate_form_errors(form)
            form = UserForm()

            context = {
                "error": True,
                "message": message,
                "form": form,
            }
    
        return render(request, 'manager/users_add.html', context=context)
    else:
        form = UserForm()
        
        context = {
            "form": form,
        }
        
    return render(request, 'manager/users_add.html', context=context)

@allow_manager
@login_required(login_url='/login/')
def users_edit(request, id):
    instance = User.objects.get(id=id)
    if request.method == 'POST':   
        form = UserForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            instance=form.save(commit=False)
            instance.save()
            
            return HttpResponseRedirect(reverse('manager:users'))
            
        else:
            message = generate_form_errors(form)
            form = UserForm()

            context = {
            "error": True,
            "message": message,
            "form": form,
            "instance": instance
            }
    
        return render(request,'manager/users_add.html', context=context)



    else:
        form = UserForm(instance=instance)
        
        context = {
            "form": form,
            "instance": instance
        }
        
    return render(request,'manager/users_add.html', context=context)


@allow_manager
@login_required(login_url='/login/')
def offers(request):
    instances = Offer.objects.all()
    
    context = {
        'instances': instances,
    }
    
    return render(request,'manager/offers.html', context=context)

@allow_manager
@login_required(login_url='/login/')

def offers_delete(request, id):
    instance = Offer.objects.get(id=id)
    
    instance.delete()
    
    return HttpResponseRedirect(reverse('manager:offers'))
@allow_manager
@login_required(login_url='/login/')
def offers_add(request):
    if request.method == 'POST':   
        form = OfferForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            
            return HttpResponseRedirect(reverse('manager:offers'))
        else:
            message = generate_form_errors(form)
            form = OfferForm()

            context = {
                "error": True,
                "message": message,
                "form": form,
            }
    
        return render(request, 'manager/offers_add.html', context=context)
    else:
        form = OfferForm()
        
        context = {
            "form": form,
        }
        
    return render(request, 'manager/offers_add.html', context=context)

@allow_manager
@login_required(login_url='/login/')
def offers_edit(request, id):
    instance = Offer.objects.get(id=id)
    if request.method == 'POST':   
        form = OfferForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            instance=form.save(commit=False)
            instance.save()
            
            return HttpResponseRedirect(reverse('manager:offers'))
            
        else:
            message = generate_form_errors(form)
            form = OfferForm()

            context = {
            "error": True,
            "message": message,
            "form": form,
            "instance": instance
            }
    
        return render(request,'manager/offers_add.html', context=context)



    else:
        form = OfferForm(instance=instance)
        
        context = {
            "form": form,
            "instance": instance
        }
        
    return render(request,'manager/offers_add.html', context=context)


@allow_manager
@login_required(login_url='/login/')
def flight(request):
    instances = Flight.objects.all()
    
    context = {
        'instances': instances,
    }
    
    
    return render(request,'manager/flight.html', context=context)
@allow_manager
@login_required(login_url='/login/')

def flight_delete(request,id):
    
    instance = Flight.objects.get(id=id)
    
    instance.delete()
    
    return HttpResponseRedirect(reverse('manager:flight'))
@allow_manager
@login_required(login_url='/login/')
def flight_add(request,):
    if request.method == 'POST':   
        form = FlightForm(request.POST, request.FILES)
        if form.is_valid():
            instance=form.save(commit=False)
            instance.save()
            
            return HttpResponseRedirect(reverse('manager:flight'))
            
        else:
            message = generate_form_errors(form)
            form = FlightForm()

            context = {
            "error": True,
            "message": message,
            "form": form,
            }
    
        return render(request,'manager/flight_add.html', context=context)



    else:
        form = FlightForm()
        
        context = {
            "form": form,
        }
        
    return render(request,'manager/flight_add.html', context=context)
@allow_manager
@login_required(login_url='/login/')
def flight_edit(request,id):
    instance = Flight.objects.get(id=id)
    if request.method == 'POST':   
        form = FlightForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():

users/views.py
from django.shortcuts import render

# Create your views here.

templates/manager/bus.html
{% extends 'base/manager-base.html' %}

{% load static %}

{% block container %}




{% include 'includes/manager-nav.html' %}


        <!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">

            <div class="row page-titles mx-0">
                <div class="col p-md-0">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Dashboard</a></li>
                        <li class="breadcrumb-item active"><a href="javascript:void(0)">Home</a></li>
                    </ol>
                </div>
            </div>
            <!-- row -->

            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">bus List</h4>
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>IMAGE</th>
                                                <th>bUS NUMBER</th>
                                                <th>DEPARTURE</th>
                                                <th>ARRIVAL</th>
                                                <th>PRICE</th>
                                                <th>EDIT</th>
                                                <th>DELETE</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for instance in instances %}
                                            <tr>
                                                <td>{{ instance.id }}</td>
                                                <td><img src="{{ instance.image.url }}" alt="instance image" style="width: 70px;"></td>
                                                <td>{{ instance.bus_numbers }}</td>
                                                <td>{{ instance.departure_code }} at {{ instance.departure_time }}</td>
                                                <td>{{ instance.arrival_code }} at {{ instance.arrival_time }}</td>
                                                <td>{{ instance.price }}</td>
                                                <td><a href="{% url 'manager:bus_edit' instance.id %}"><button type="button" class="btn btn-primary">Edit</button></a></td>
                                                <td><a href="{% url 'manager:bus_delete' instance.id %}"><button type="button" class="btn btn-danger">Delete</button></a></td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #/ container -->
        </div>
        <!--**********************************
            Content body end
        ***********************************-->
        
        
        <!--**********************************
            Footer start
        ***********************************-->
        <div class="footer">
            <div class="copyright">
                <p>Copyright &copy; Designed & Developed by <a href="https://themeforest.net/user/quixlab">Quixlab</a> 2018</p>
            </div>
        </div>
        <!--**********************************
            Footer end
        ***********************************-->

{% endblock %}

templates/manager/flight.html
{% extends 'base/manager-base.html' %}

{% load static %}

{% block container %}




{% include 'includes/manager-nav.html' %}


        <!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">

            <div class="row page-titles mx-0">
                <div class="col p-md-0">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Dashboard</a></li>
                        <li class="breadcrumb-item active"><a href="javascript:void(0)">Home</a></li>
                    </ol>
                </div>
            </div>
            <!-- row -->

            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Flight List</h4>
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>IMAGE</th>
                                                <th>FLIGHT NUMBER</th>
                                                <th>DEPARTURE</th>
                                                <th>ARRIVAL</th>
                                                <th>PRICE</th>
                                                <th>EDIT</th>
                                                <th>DELETE</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for instance in instances %}
                                            <tr>
                                                <td>{{ instance.id }}</td>
                                                <td><img src="{{ instance.image.url }}" alt="instance image" style="width: 70px;"></td>
                                                <td>{{ instance.flight_numbers }}</td>
                                                <td>{{ instance.departure_code }} at {{ instance.departure_time }}</td>
                                                <td>{{ instance.arrival_code }} at {{ instance.arrival_time }}</td>
                                                <td>{{ instance.price }}</td>
                                                <td><a href="{% url 'manager:bus_edit' instance.id %}"><button type="button" class="btn btn-primary">Edit</button></a></td>
                                                <td><a href="{% url 'manager:bus_delete' instance.id %}"><button type="button" class="btn btn-danger">Delete</button></a></td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #/ container -->
        </div>
        <!--**********************************
            Content body end
        ***********************************-->
        
        
        <!--**********************************
            Footer start
        ***********************************-->
        <div class="footer">
            <div class="copyright">
                <p>Copyright &copy; Designed & Developed by <a href="https://themeforest.net/user/quixlab">Quixlab</a> 2018</p>
            </div>
        </div>
        <!--**********************************
            Footer end
        ***********************************-->

{% endblock %}

templates/manager/login.html
{% extends 'base/manager-base.html' %}
{% load static %}
{% block container %}

<div class="container-fluid" style="padding-top: 200px;">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Manager Login</h4>
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_email">Email</label>
                            {{ form.email }}
                        </div>
                        <div class="form-group">
                            <label for="id_password">Password</label>
                            {{ form.password }}
                        </div>
                        <button type="submit" class="btn btn-primary">Login</button>
                    </form>
                    {% if form.errors %}
                        <div class="alert alert-danger mt-3">
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <p>{{ error }}</p>
                                {% endfor %}
                            {% endfor %}
                            {% for error in form.non_field_errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/manager/offers.html
{% extends 'base/manager-base.html' %}

{% load static %}

{% block container %}




{% include 'includes/manager-nav.html' %}


        <!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">

            <div class="row page-titles mx-0">
                <div class="col p-md-0">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Dashboard</a></li>
                        <li class="breadcrumb-item active"><a href="javascript:void(0)">Home</a></li>
                    </ol>
                </div>
            </div>
            <!-- row -->

            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Offer List</h4>
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered zero-configuration">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>CODE</th>
                                                <th>DISCOUNT</th>
                                                <th>DESCEIBTION</th>
                                                <th>PERCENTAGE</th>
                                                <th>EDIT</th>
                                                <th>DELETE</th>
                                            </tr>
                                        </thead>
                                    <tbody>
                                        {% for instance in instances %}
                                        <tr>
                                            <td>{{instance.id}}</td>
                                            <td>{{instance.code}}</td>
                                            <td>{{instance.discount}}</td>
                                            <td>{{instance.short_description}}</td>
                                            <td>{{instance.is_percentage}}</td>
                                            <td><a href="{% url 'manager:offers_edit' id=instance.id %}"><button type="button" class="btn mb-1 btn-primary">Edit</button></a></td>
                                            <td><a href="{% url 'manager:offers_delete' id=instance.id %}"><button type="button" class="btn mb-1 btn-danger" >Delete</button></a></td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #/ container -->
        </div>
        <!--**********************************
            Content body end
        ***********************************-->
        
        
        <!--**********************************
            Footer start
        ***********************************-->
        <div class="footer">
            <div class="copyright">
                <p>Copyright &copy; Designed & Developed by <a href="https://themeforest.net/user/quixlab">Quixlab</a> 2018</p>
            </div>
        </div>
        <!--**********************************
            Footer end
        ***********************************-->

{% endblock %}

templates/manager/slider.html
{% extends 'base/manager-base.html' %}

{% load static %}

{% block container %}




{% include 'includes/manager-nav.html' %}


        <!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">

            <div class="row page-titles mx-0">
                <div class="col p-md-0">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Dashboard</a></li>
                        <li class="breadcrumb-item active"><a href="javascript:void(0)">Home</a></li>
                    </ol>
                </div>
            </div>
            <!-- row -->

            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Slider List</h4>
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered zero-configuration">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>NAME</th>
                                                <th>IMAGE</th>
                                                <th>EDIT</th>
                                                <th>DELETE</th>
                                            </tr>
                                        </thead>
                                    <tbody>
                                        {% for instance in instances %}
                                        <tr>
                                            <td>{{instance.id}}</td>
                                            <td>{{instance.name}}</td>
                                            <td><img src="{{instance.image.url}}" alt="image" style="width: 70px;"></td>
                                            <td><a href="{% url 'manager:slider_edit' id=instance.id %}"><button type="button" class="btn mb-1 btn-primary">Edit</button></a></td>
                                            <td><a href="{% url 'manager:slider_delete' id=instance.id %}"><button type="button" class="btn mb-1 btn-danger" >Delete</button></a></td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #/ container -->
        </div>
        <!--**********************************
            Content body end
        ***********************************-->
        
        
        <!--**********************************
            Footer start
        ***********************************-->
        <div class="footer">
            <div class="copyright">
                <p>Copyright &copy; Designed & Developed by <a href="https://themeforest.net/user/quixlab">Quixlab</a> 2018</p>
            </div>
        </div>
        <!--**********************************
            Footer end
        ***********************************-->

{% endblock %}